version: '3'
services:
  jenkins-sshd:
    build: .
    image: yi/jenkins-ssh:0.0
    container_name: jenkins-ssh
    ports:
        - "8080:8080"
        - "22:37000"
    volumes:
        - "/media:/media"
        - "/var/run/docker.sock:/var/run/docker.sock"
