version: '3'
services:
  jenkins-vsftpd-sshd:
    build: .
    image: yi/jenkins-ftp-ssh:0.0
    container_name: jenkins-ftp-ssh
    ports:
        - "8080:8080"
        - "37000:22"
        - "20-21:20-21"
        - "65500-65515:65500-65515"
    volumes:
        - "/media/common/DOCKER_IMAGES/Tensorflow:/var/ftp:ro"
        - "/media:/media"
        - "/var/run/docker.sock:/var/run/docker.sock"
