version: '3'
services:
  jenkins-vsftpd-sshd:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        USER_ID: ${USER_ID:-0}
        GROUP_ID: ${GROUP_ID:-0}
        TOMCAT_VER: 8.5.61
    image: yi/jenkins-ftp-ssh:0.0
    privileged: true
    container_name: jenkins-ftp-ssh
    ports:
        - "8080:8080"
        - "37000:22"
        - "20-21:20-21"
        - "65500-65515:65500-65515"
    volumes:
        - "/software/releases:/var/ftp:ro"
        - "~/.ssh/hls1-bmc:/root/.ssh/hls1-bmc:ro"
        - "~/.ssh/hls1-bmc.pub:/root/.ssh/hls1-bmc.pub:ro"
        - "~/.ssh/kvm-srv:/root/.ssh/kvm-srv:ro"
        - "~/.ssh/kvm-srv.pub:/root/.ssh/kvm-srv.pub:ro"
        - "~/.ssh/vm-srv:/root/.ssh/vm-srv:ro"
        - "~/.ssh/vm-srv.pub:/root/.ssh/vm-srv.pub:ro"
        - "~/.ssh/hls1-vm-jenkins:/root/.ssh/hls1-vm-jenkins:ro"
        - "~/.ssh/hls1-vm-jenkins.pub:/root/.ssh/hls1-vm-jenkins.pub:ro"
        - "/software:/software"
        - "/tools:/tools"
        - "/var/run/docker.sock:/var/run/docker.sock"
