#!/bin/bash

set -e

ANON_ROOT=${ANON_ROOT:-/var/ftp}
MAX_PORT=${MAX_PORT:-65515}
MIN_PORT=${MIN_PORT:-65500}
MAX_PER_IP=${MAX_PER_IP:-2}
MAX_LOGIN_FAILS=${MAX_LOGIN_FAILS:-2}
MAX_CLIENTS=${MAX_CLIENTS:-50}
MAX_RATE=${MAX_RATE:-0}
FTPD_BANNER=${FTPD_BANNER:-"Welcome To YI Public FTP Server"}


[ -f /etc/vsftpd.conf ] || cat <<EOF > /etc/vsftpd.conf
listen=YES
# Allow anonymous FTP? (Disabled by default).
anonymous_enable=YES
# Stop prompting for a password on the command line
no_anon_password=YES
#Show the user and group as ftp:ftp, regardless of the owner
hide_ids=YES
# This directory is used as a secure chroot() jail at times vsftpd does not require filesystem access.
secure_chroot_dir=/var/run/vsftpd/empty
# If enabled, users of the FTP server can be shown messages when they first enter a new directory
dirmessage_enable=YES
# If enabled, vsftpd will display directory listings with the time in your local time zone
use_localtime=YES
# Controls whether PORT style data connections use port 20 (ftp-data) on the server machine.
connect_from_port_20=YES
# Controls whether any FTP commands which change the filesystem are allowed or not
write_enable=NO
# Turning off Linux's newer Seccomp-BPF mechanism for better compatibility
seccomp_sandbox=NO
# Enable logging ftp-related info
xferlog_std_format=NO
log_ftp_protocol=YES
#Point anonymous user to the ftp root directory
anon_root=${ANON_ROOT}
# Limit the range of ports that can be used for passive FTP
pasv_max_port=${MAX_PORT}
pasv_min_port=${MIN_PORT}
# Limit maximum number of clients which may be connected from the same source internet address
max_per_ip=${MAX_PER_IP}
# After this many login failures, the session is killed
max_login_fails=${MAX_LOGIN_FAILS}
# Limit maximum number of clients which may be connected. The value 0 switches off the limit
max_clients=${MAX_CLIENTS}
# Limit maximum data transfer rate permitted, in bytes per second, for anonymous clients. The value 0 switches off the limit
anon_max_rate=${MAX_RATE}
# Set the greeting banner displayed by vsftpd when a connection first comes in.
ftpd_banner=${FTPD_BANNER}
EOF

# Remove any trailing space and CR characters from /etc/vsftpd.conf
sed -i 's,\r,,;s, *$,,' /etc/vsftpd.conf

/usr/sbin/vsftpd "$@"
