#!/bin/bash

# Check the status of sshd service and start it if not running

case "$(pidof sshd | wc -w)" in

0)  echo "RESTARTING SSHD SERVICE:"
    /etc/init.d/ssh start
    ;;
5)  echo "SSHD SERVICE RUNNING"
    ;;
esac

# Starting TomCat Service

/bin/bash /opt/tomcat/bin/catalina.sh run
